### ISSUE TITLE
Parameterize ImageHandler

### ISSUE THREAD

**Issue by KoenigKrote** [MEC402/tileViewer#13]
Right now ImageHandler is generating texture atlases and parsing directories for files hardcoded, we need it to be able to read a directory, determine what the highest depth level will be, allocate that-much-memory in the atlas for that face, then start loading in the texture levels as appropriate (probably also hand back a maxDepthLevel for us to use to generate the cube as well?)

**Comment by KoenigKrote** [comment]
We're still hardcoding image width/height at 512x512, either that's fine (and they should be replaced with a CONST) or we need to determine at runtime

**Comment by KoenigKrote** [comment]
Doesn't seem like these values will change any time soon.  Replaced with constants. 7914b56f2515e91fd26cfd7e330c788d3020d174

**Comment by smcutchin** [comment]
We could place the tile size information into the panoramas.json file.

**Comment by KoenigKrote** [comment]
Opened #29
